name: Cleanup

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !contains(fromJSON('["main", "master", "develop"]'), github.event.pull_request.head.ref) }}
        run: |
          echo "${{ github.event.pull_request.head.ref }}"
      - run: |
          echo "Complete"
